#!/usr/bin/perl
### !/bin/bash
use strict;
my $message;
my $Prompt;
my $got_pass=0;

open(my $auth, "<", glob("~/.authinfo")) or die "No .authinfo in your HOME";
while (<$auth>) {
    print $auth;
    print "\n----\n";
    my @fields = split;
    my ($machine, $authuser, $pass, $authport) = @fields[1, 3, 5, 7];
    print $machine, "-", $authuser, "-", $pass, "-", $authport;
}
