#!/bin/bash
echo "shell is not ready"
exit 0

sudo rm -rf /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk

sudo rm -rf /Library/PreferencePanes/JavaControlPanel.prefPane

sudo rm -rf /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin

sudo rm -rf ~/Library/Application\ Support/Java

sudo rm -rf /Library/LaunchAgents/com.oracle.java.Java-Updater.plist

sudo rm -rf /Library/PrivilegedHelperTools/com.oracle.java.JavaUpdateHelper

sudo rm -rf /Library/LaunchDaemons/com.oracle.java.Helper-Tool.plist

sudo rm -rf /Library/Preferences/com.oracle.java.Helper-Tool.plist