#!/bin/bash

pathTxt=`printf $1`
set -o pipefail
set +e
echo $pathTxt | grep ":" > /dev/null 2>&1
if test $? -gt 0;then
    path=`echo "$pathTxt" | sed -e 's/\//\\\/g'`
else
    path=`echo "$pathTxt" | cut -d ":" -f2- | sed -e 's/\//\\\/g'`
fi
echo "$path"
